services:
  nextcloud:
    image: nextcloud:production-apache
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - cloud
    depends_on:
      - nextclouddb
      - redis
      - elasticsearch
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ./nextcloud/html:/var/www/html
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data

    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=2G
      - PHP_UPLOAD_LIMIT=2G
      - NEXTCLOUD_MEMORY_LIMIT=2G
      - OPCACHE_ENABLE=1
      - APACHE_BODY_LIMIT=2GB

  nextclouddb:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - cloud
    volumes:
      - ./mariadb/nextclouddb:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQLD_INNODB_BUFFER_POOL_SIZE=22G
      - MYSQLD_INNODB_LOG_FILE_SIZE=5G

  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    networks:
      - cloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - password=password
      - username=nextcloud
      - domain=localhost
      - extra_params=--o:ssl.enable=true
    ports:
      - 9980:9980

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes --maxmemory 4G
    volumes:
      - ./redis/data:/data
    networks:
      - cloud

  nginx-proxy:
    # image: 'jc21/nginx-proxy-manager:latest'
    image: 'nginxinc/nginx-unprivileged:stable-alpine'
    container_name: nginx-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/ssl/:/etc/ssl/nextcloud/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt:/etc/letsencrypt

    networks:
      - cloud
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    networks:
      - cloud
    command: sh -c "/bin/tini -s /usr/local/bin/docker-entrypoint.sh eswrapper"
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      #- "ES_JAVA_OPTS=-Xms512m -Xmx2048m"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      #- "xpack.security.transport.ssl.enabled=true"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    user: 1000:1000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/logs/:/usr/share/elasticsearch/logs/

networks:
  cloud:
    name: cloud
    driver: bridge
